{elm/boolean blaze.elm.literal/boolean
 elm/decimal blaze.elm.literal/decimal
 elm/integer blaze.elm.literal/integer
 elm/string blaze.elm.literal/string
 elm/tuple blaze.elm.literal/tuple
 elm/instance blaze.elm.literal/instance
 elm/code blaze.elm.literal/code
 elm/code-ref blaze.elm.literal/code-ref
 elm/quantity blaze.elm.literal/quantity
 elm/expression-ref blaze.elm.literal/expression-ref
 elm/equal blaze.elm.literal/equal
 elm/equivalent blaze.elm.literal/equivalent
 elm/greater blaze.elm.literal/greater
 elm/greater-or-equal blaze.elm.literal/greater-or-equal
 elm/less blaze.elm.literal/less
 elm/less-or-equal blaze.elm.literal/less-or-equal
 elm/and blaze.elm.literal/and
 elm/not blaze.elm.literal/not
 elm/or blaze.elm.literal/or
 elm/xor blaze.elm.literal/xor
 elm/is-false blaze.elm.literal/is-false
 elm/is-null blaze.elm.literal/is-null
 elm/is-true blaze.elm.literal/is-true
 elm/list blaze.elm.literal/list
 elm/if blaze.elm.literal/if-expr
 elm/abs blaze.elm.literal/abs
 elm/add blaze.elm.literal/add
 elm/ceiling blaze.elm.literal/ceiling
 elm/divide blaze.elm.literal/divide
 elm/exp blaze.elm.literal/exp
 elm/floor blaze.elm.literal/floor
 elm/log blaze.elm.literal/log
 elm/ln blaze.elm.literal/ln
 elm/modulo blaze.elm.literal/modulo
 elm/multiply blaze.elm.literal/multiply
 elm/negate blaze.elm.literal/negate
 elm/power blaze.elm.literal/power
 elm/predecessor blaze.elm.literal/predecessor
 elm/round blaze.elm.literal/round
 elm/subtract blaze.elm.literal/subtract
 elm/date blaze.elm.literal/date
 elm/date-from blaze.elm.literal/date-from
 elm/date-time blaze.elm.literal/date-time
 elm/time blaze.elm.literal/time
 elm/interval blaze.elm.literal/interval
 elm/intersect blaze.elm.literal/intersect
 elm/current blaze.elm.literal/current
 elm/singleton-from blaze.elm.literal/singleton-from
 elm/as blaze.elm.literal/as
 elm/convert-quantity blaze.elm.literal/convert-quantity
 elm/children blaze.elm.literal/children
 elm/descendents blaze.elm.literal/descendents
 elm/to-date blaze.elm.literal/to-date
 elm/to-date-time blaze.elm.literal/to-date-time
 elm/to-decimal blaze.elm.literal/to-decimal
 elm/to-integer blaze.elm.literal/to-integer
 elm/to-list blaze.elm.literal/to-list
 elm/to-quantity blaze.elm.literal/to-quantity
 elm/to-string blaze.elm.literal/to-string
 elm/calculate-age-at blaze.elm.literal/calculate-age-at}
