{elm/boolean blaze.elm.literals/boolean
 elm/dec blaze.elm.literals/dec
 elm/int blaze.elm.literals/int
 elm/string blaze.elm.literals/string
 elm/code blaze.elm.literals/code
 elm/quantity blaze.elm.literals/quantity
 elm/equal blaze.elm.literals/equal
 elm/greater blaze.elm.literals/greater
 elm/greater-or-equal blaze.elm.literals/greater-or-equal
 elm/less blaze.elm.literals/less
 elm/less-or-equal blaze.elm.literals/less-or-equal
 elm/not-equal blaze.elm.literals/not-equal
 elm/list blaze.elm.literals/list
 elm/if blaze.elm.literals/if-expr
 elm/add blaze.elm.literals/add
 elm/divide blaze.elm.literals/divide
 elm/multiply blaze.elm.literals/multiply
 elm/negate blaze.elm.literals/negate
 elm/subtract blaze.elm.literals/subtract
 elm/date blaze.elm.literals/date
 elm/date-time blaze.elm.literals/date-time
 elm/time blaze.elm.literals/time
 elm/interval blaze.elm.literals/interval
 elm/current blaze.elm.literals/current
 elm/as blaze.elm.literals/as
 elm/tuple blaze.elm.literals/tuple
 elm/singleton-from blaze.elm.literals/singleton-from}
