codecov:
  branch: main

coverage:
  status:
    project:
      default:
        target: auto
        threshold: "0.1"
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
