services:
  keycloak:
    image: "quay.io/keycloak/keycloak:26.3.0@sha256:08a31919cfcd814bf1b465142b1a716c4d1a8830f772bb5c9dffcbd96de3fba6"
    command: "start-dev --import-realm --health-enabled=true"
    ports:
    - "8090:8080"
    volumes:
    - "${GITHUB_WORKSPACE}/.github/openid-auth-test/realm:/opt/keycloak/data/import"
  blaze:
    image: "blaze:latest"
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx1g"
      OPENID_PROVIDER_URL: "http://keycloak:8080/realms/blaze"
    ports:
    - "8080:8080"
    volumes:
    - "blaze-data:/app/data"
    depends_on:
    - keycloak
volumes:
  blaze-data:
