services:
  keycloak:
    image: "quay.io/keycloak/keycloak:26.2.4@sha256:4a81762677f8911c6266e3dea57a2d78fa17bd63408debbf23afd8cc46fe256e"
    command: "start-dev --import-realm --health-enabled=true"
    ports:
    - "8090:8080"
    volumes:
    - "${GITHUB_WORKSPACE}/.github/openid-auth-test/realm:/opt/keycloak/data/import"
  blaze:
    image: "blaze:latest"
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx1g"
      OPENID_PROVIDER_URL: "http://keycloak:8080/realms/blaze"
    ports:
    - "8080:8080"
    volumes:
    - "blaze-data:/app/data"
    depends_on:
    - keycloak
volumes:
  blaze-data:
