services:
  keycloak:
    image: "quay.io/keycloak/keycloak:26.3.3@sha256:6a7217a100bd3e5de4063a27a538ef999a3c5a88c4b4ec0ffc0a642aee7b2597"
    command: "start-dev --import-realm --health-enabled=true"
    ports:
    - "8090:8080"
    volumes:
    - "${GITHUB_WORKSPACE}/.github/openid-auth-test/realm:/opt/keycloak/data/import"
  blaze:
    image: "blaze:latest"
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx1g"
      OPENID_PROVIDER_URL: "http://keycloak:8080/realms/blaze"
    ports:
    - "8080:8080"
    volumes:
    - "blaze-data:/app/data"
    depends_on:
    - keycloak
volumes:
  blaze-data:
