services:
  keycloak:
    image: "jboss/keycloak:15.0.2@sha256:d8ed1ee5df42a178c341f924377da75db49eab08ea9f058ff39a8ed7ee05ec93"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/realm.json
    ports:
    - "8090:8080"
    volumes:
    - "../../.github/openid-auth-test/realm.json:/tmp/realm.json"
  blaze:
    image: "samply/blaze:0.22@sha256:97f9b80ca8db6706d0c4e2c82f3a2133f0fc3527d60e0603784665715a280744"
    environment:
      BASE_URL: "http://localhost:8080"
      JAVA_TOOL_OPTIONS: "-Xmx2g"
      OPENID_PROVIDER_URL: "http://keycloak:8080/auth/realms/blaze"
    ports:
    - "8080:8080"
    volumes:
    - "blaze-data:/app/data"
    depends_on:
    - keycloak
volumes:
  blaze-data:
