{fhir/integer clojure.core/int
 fhir/long clojure.core/long
 fhir/uri blaze.fhir.spec.type/->Uri
 fhir/url blaze.fhir.spec.type/->Url
 fhir/canonical blaze.fhir.spec.type/->Canonical
 fhir/base64Binary blaze.fhir.spec.type/->Base64Binary
 fhir/date blaze.fhir.spec.type/->Date
 fhir/dateTime blaze.fhir.spec.type/->DateTime
 fhir/time blaze.fhir.spec.type/->Time
 fhir/code blaze.fhir.spec.type/->Code
 fhir/oid blaze.fhir.spec.type/->Oid
 fhir/id blaze.fhir.spec.type/->Id
 fhir/markdown blaze.fhir.spec.type/->Markdown
 fhir/unsignedInt blaze.fhir.spec.type/->UnsignedInt
 fhir/positiveInt blaze.fhir.spec.type/->PositiveInt
 fhir/uuid blaze.fhir.spec.type/->Uuid
 fhir/xhtml blaze.fhir.spec.type/->Xhtml}
