name: "Download File from Speicherwolke with Caching"

inputs:
  token:
    required: true
  filename:
    required: true

runs:
  using: composite
  steps:
    - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
      with:
        key: ${{ inputs.filename }}
        path: ${{ inputs.filename }}

    - shell: bash
      env:
        TOKEN: ${{ inputs.token }}
        FILENAME: ${{ inputs.filename }}
      run: |
        if [ -f "$FILENAME" ]; then
          echo "File $FILENAME was loaded from cache."
        else
          echo "Downloading $FILENAME..."
          wget -q https://speicherwolke.uni-leipzig.de/index.php/s/$TOKEN/download/$FILENAME
        fi
