services:
  keycloak:
    image: 'quay.io/keycloak/keycloak:26.3.4@sha256:2b32a51a31e8d780d9fa9a69a59ead69975263c61b5dd13559090e22aa26f100'
    command: 'start-dev --import-realm'
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      HTTP_PORT: 8095
    ports:
      - '8095:8080'
    volumes:
      - './keycloak/import:/opt/keycloak/data/import'
