services:
  keycloak:
    image: 'quay.io/keycloak/keycloak:26.4.1@sha256:bbb299c7e58a2c61c683dc3439da3e2698e005ca88ba6fd249629311d70250ab'
    command: 'start-dev --import-realm'
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      HTTP_PORT: 8095
    ports:
      - '8095:8080'
    volumes:
      - './keycloak/import:/opt/keycloak/data/import'
