services:
  keycloak:
    image: 'quay.io/keycloak/keycloak:26.4.0@sha256:5f3fb534cde6bf006d79f5912473e5d2c828c707cdfc52e16972803aca9d43dd'
    command: 'start-dev --import-realm'
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      HTTP_PORT: 8095
    ports:
      - '8095:8080'
    volumes:
      - './keycloak/import:/opt/keycloak/data/import'
