services:
  keycloak:
    image: 'quay.io/keycloak/keycloak:26.3.3@sha256:6a7217a100bd3e5de4063a27a538ef999a3c5a88c4b4ec0ffc0a642aee7b2597'
    command: 'start-dev --import-realm'
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      HTTP_PORT: 8095
    ports:
      - '8095:8080'
    volumes:
      - './keycloak/import:/opt/keycloak/data/import'
