services:
  keycloak:
    image: 'quay.io/keycloak/keycloak:26.3.0@sha256:08a31919cfcd814bf1b465142b1a716c4d1a8830f772bb5c9dffcbd96de3fba6'
    command: 'start-dev --import-realm'
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      HTTP_PORT: 8095
    ports:
      - '8095:8080'
    volumes:
      - './keycloak/import:/opt/keycloak/data/import'
