services:
  ingress:
    image: "nginx:1.29.1@sha256:d5f28ef21aabddd098f3dbc21fe5b7a7d7a184720bc07da0b6c9b9820e97f25e"
    environment:
      BLAZE_HOST: "blaze.localhost"
      KEYCLOAK_HOST: "keycloak.localhost"
    ports:
    - "443:443"
    volumes:
    - "../ingress/default.conf.template:/etc/nginx/templates/default.conf.template:ro"
    - "../ingress/blaze-cert.pem:/etc/nginx/conf.d/blaze-cert.pem:ro"
    - "../ingress/blaze-key.pem:/etc/nginx/conf.d/blaze-key.pem:ro"
    - "../ingress/keycloak-cert.pem:/etc/nginx/conf.d/keycloak-cert.pem:ro"
    - "../ingress/keycloak-key.pem:/etc/nginx/conf.d/keycloak-key.pem:ro"

  frontend:
    image: "blaze-frontend:latest"
    environment:
      ORIGIN: "https://blaze.localhost"
      BACKEND_BASE_URL: "http://backend:8080"
      AUTH_CLIENT_ID: "account"
      AUTH_CLIENT_SECRET: "e11a3a8e-6e24-4f9d-b914-da7619e8b31f"
      AUTH_ISSUER: "https://keycloak.localhost/realms/blaze"
      AUTH_SECRET: "666df42c74ce1f4728fe2ffe99b146e0f2e4b4f9810594fcf68c0330495bca0f"
      PROTOCOL_HEADER: "x-forwarded-proto"
      HOST_HEADER: "x-forwarded-host"
      NODE_EXTRA_CA_CERTS: "/app/keycloak-cert.pem"
    extra_hosts:
    - "keycloak.localhost:host-gateway"
    volumes:
    - "../ingress/keycloak-cert.pem:/app/keycloak-cert.pem:ro"
    deploy:
      replicas: 2

  backend:
    image: "blaze:latest"
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx4g"
      LOG_LEVEL: "debug"
      ENABLE_ADMIN_API: "true"
      ENABLE_TERMINOLOGY_SERVICE: "true"
      ENABLE_TERMINOLOGY_LOINC: "true"
      DB_RESOURCE_CACHE_SIZE: "10000"
      OPENID_PROVIDER_URL: "https://keycloak.localhost/realms/blaze"
      OPENID_CLIENT_TRUST_STORE: "/app/keycloak-trust-store.p12"
      OPENID_CLIENT_TRUST_STORE_PASS: "insecure"
    extra_hosts:
    - "keycloak.localhost:host-gateway"
    volumes:
    - "blaze-data:/app/data"
    - "../ingress/keycloak-trust-store.p12:/app/keycloak-trust-store.p12:ro"

  keycloak:
    image: "quay.io/keycloak/keycloak:24.0.5@sha256:f8ade94c1d0ad2f2fa7734a455fee5392764f402c43ca35e9af6bf63a2541dc9"
    command: "start --import-realm --hostname=keycloak.localhost --proxy-headers forwarded --http-enabled true"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
    - "./keycloak/import:/opt/keycloak/data/import"

volumes:
  blaze-data:
