services:
  keycloak:
    image: "quay.io/keycloak/keycloak:26.4.2@sha256:3617b09bb4b7510a8d8d9b9fc5707399e2d70688dbcc2f8fb013a144829be1b9"
    command: "start-dev --import-realm --health-enabled=true"
    ports:
    - "8090:8080"
    volumes:
    - "${GITHUB_WORKSPACE}/.github/openid-auth-test/realm:/opt/keycloak/data/import"
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000; echo -e 'GET /health/ready HTTP/1.1\r\nHost: localhost:9000\r\nConnection: close\r\n\r\n' >&3; grep -q '\"status\": \"UP\"' <&3" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  data-server:
    image: "blaze:latest"
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx2g"
      DB_BLOCK_CACHE_SIZE: "2048"
      DB_SCALE_FACTOR: "2"
      EXTERN_TERMINOLOGY_SERVICE_URL: "http://terminology-server:8080/fhir"
      EXTERN_TERMINOLOGY_SERVICE_OPENID_PROVIDER_URL: "http://keycloak:8080/realms/blaze"
      EXTERN_TERMINOLOGY_SERVICE_OPENID_CLIENT_ID: "account"
      EXTERN_TERMINOLOGY_SERVICE_OPENID_CLIENT_SECRET: "e11a3a8e-6e24-4f9d-b914-da7619e8b31f"
      LOG_LEVEL: "debug"
    ports:
    - "8080:8080"
    volumes:
    - "blaze-data:/app/data"
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      keycloak:
        condition: service_healthy

  terminology-server:
    image: "blaze:latest"
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx5g"
      ENABLE_TERMINOLOGY_SERVICE: "true"
      ENABLE_TERMINOLOGY_LOINC: "true"
      ENABLE_TERMINOLOGY_SNOMED_CT: "true"
      SNOMED_CT_RELEASE_PATH: "/app/sct-release"
      OPENID_PROVIDER_URL: "http://keycloak:8080/realms/blaze"
      LOG_LEVEL: "debug"
    ports:
    - "8081:8081"
    - "8082:8080"
    volumes:
    - "blaze-terminology-data:/app/data"
    - "./SnomedCT_InternationalRF2_PRODUCTION_20250701T120000Z:/app/sct-release"
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      keycloak:
        condition: service_healthy

volumes:
  blaze-data:
  blaze-terminology-data:
