#!/bin/bash
set -euo pipefail

# Blaze mints canonical URLs like https://blaze-server.org/fhir/StructureDefinition/Job,
# but the IG Publisher renders that artifact to StructureDefinition-Job.html. The
# slashed canonical path therefore has no file behind it and would 404.
#
# HL7 solves this with server-side rewrite rules. GitHub Pages has none, so this
# script materialises each canonical path as a redirect page next to the
# rendering. GitHub Pages serves /fhir/StructureDefinition/Job from the file
# StructureDefinition/Job.html, so the canonical resolves without a further
# redirect of its own. Redirect targets are relative, which keeps a copy of the
# site under a versioned prefix working.
#
# The publisher's own flat layout is deliberately left alone. Its pages carry
# hundreds of root-relative references to tbl_*.png, icons and assets/, so
# moving them into per-type directories would break the rendering and every
# inbound link along with it.
#
# Usage: generate-canonical-redirects.sh <output-dir>

output_dir="${1:?usage: generate-canonical-redirects.sh <output-dir>}"
canonical="https://blaze-server.org/fhir"
marker="<!-- generated by generate-canonical-redirects.sh -->"

count=0

for resource in "$output_dir"/*.json; do
  name="$(basename "$resource" .json)"
  page="$name.html"

  # Only rendered artifacts are worth redirecting to. This also skips the
  # publisher's own JSON output, such as qa.json or fhir.schema.json.
  [ -f "$output_dir/$page" ] || continue

  url="$(jq -r 'if type == "object" then .url // empty else empty end' "$resource")"

  case "$url" in
  "$canonical"/*) ;;
  *) continue ;;
  esac

  path="${url#"$canonical"/}"
  dir="$(dirname "$path")"
  redirect="$output_dir/$path.html"

  # Rerunning the script overwrites its own output, but never a file the
  # publisher put there, which would mean the two layouts have started to
  # collide.
  if [ -e "$redirect" ] && ! head -n 1 "$redirect" | grep -qF "$marker"; then
    echo "$redirect already exists, refusing to overwrite publisher output." >&2
    exit 1
  fi

  # One ../ per directory segment, to get back to the site root from the
  # redirect. A canonical without a slash sits in the root already.
  up=""
  if [ "$dir" != "." ]; then
    for _ in $(echo "$dir" | tr '/' ' '); do
      up="../$up"
    done
  fi

  mkdir -p "$output_dir/$dir"
  cat >"$redirect" <<EOF
$marker
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="refresh" content="0; url=$up$page">
<link rel="canonical" href="$url">
<title>$name</title>
</head>
<body>
<p>Redirecting to <a href="$up$page">$name</a>.</p>
</body>
</html>
EOF

  count=$((count + 1))
done

echo "Generated $count canonical redirects in $output_dir."
