services:
  data-server:
    image: "blaze:latest"
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx2g"
      EXTERN_TERMINOLOGY_SERVICE_URL: "http://terminology-server:8080/fhir"
    ports:
    - "8080:8080"
    volumes:
    - "blaze-data:/app/data"
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  terminology-server:
    image: "blaze:latest"
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx8g"
      ENABLE_TERMINOLOGY_SERVICE: "true"
      ENABLE_TERMINOLOGY_LOINC: "true"
      ENABLE_TERMINOLOGY_SNOMED_CT: "true"
      SNOMED_CT_RELEASE_PATH: "/app/sct-release"
    ports:
    - "8082:8080"
    volumes:
    - "blaze-terminology-data:/app/data"
    - "./SnomedCT_InternationalRF2_PRODUCTION_20250701T120000Z:/app/sct-release"
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  fhir-validator:
    image: "ghcr.io/medizininformatik-initiative/mii-fhir-validator:0.0.1-alpha.3"
    environment:
      JAVA_OPTS: "-Xmx2g"
      TX_SERVER: "http://terminology-server:8080/fhir"
    ports:
    - "8084:8080"
    volumes:
    - ./fhir-settings.json:/app/fhir-settings.json:ro
    depends_on:
      terminology-server:
        condition: service_healthy

volumes:
  blaze-data:
  blaze-terminology-data:
