= Blaze
Alexander Kiel <akiel@life.uni-leipzig.de>
:toc: left
:source-highlighter: coderay

== Goal

The goal of this project is to provide a FHIR® Store with an internal CQL Evaluation Engine which is able to answer population wide aggregate queries in a timely manner to enable interactive, online queries.

== Installation

You can use one of our sample https://docs.docker.com/compose/[Docker Compose] files to bring up Blaze or install it manually.

=== Docker

The most convenient way is to check out this repository and use the `docker-compose.yml` to bring Blaze up. The default minimum memory requirements are 4 GB. You have to change the memory settings for Blaze and Datomic if you have less memory available. You also need to have port 8080 free on your host.

To start Blaze, type:

```bash
docker-compose up
```

You should see a output similar to:

```
Creating volume "blaze_db-data" with default driver
Recreating blaze_db_1 ... done
Recreating blaze_store_1 ... done
Attaching to blaze_db_1, blaze_store_1
db_1     | Launching with Java options -server -Xms1g -Xmx1g -XX:+UseG1GC -XX:MaxGCPauseMillis=50
db_1     | Starting datomic:free://0.0.0.0:4334/<DB-NAME>, storing data in: /data ...
db_1     | System started datomic:free://0.0.0.0:4334/<DB-NAME>, storing data in: /data
store_1  | 19-05-13 08:51:03 1ad81424eddb INFO [blaze.system:109] - Read structure definitions from: /app/fhir/r4/structure-definitions resulting in: Address, UsageContext, Annotation, Age, Attachment, Period, ContactDetail, DataRequirement, CodeableConcept, Organization, Encounter, CodeSystem, TriggerDefinition, Count, Specimen, Bundle, Expression, Coding, Dosage, Patient, Range, ContactPoint, Signature, RelatedArtifact, Timing, Meta, Quantity, Distance, HumanName, DeviceMetric, Duration, Money, SampledData, Ratio, Resource, Condition, Extension, ParameterDefinition, ServiceRequest, Device, Reference, Identifier, Narrative, Observation, Contributor
store_1  | 19-05-13 08:51:09 1ad81424eddb INFO [blaze.system:89] - Created database at: datomic:free://db:4334/dev?password=datomic
store_1  | 19-05-13 08:51:09 1ad81424eddb INFO [blaze.system:92] - Connect with database: datomic:free://db:4334/dev?password=datomic
store_1  | 19-05-13 08:51:12 1ad81424eddb INFO [blaze.system:97] - Upsert schema in database: datomic:free://db:4334/dev?password=datomic creating 10194 new facts
store_1  | 19-05-13 08:51:12 1ad81424eddb INFO [blaze.server:33] - Start server on port 8080
store_1  | 19-05-13 08:51:12 1ad81424eddb INFO [blaze.core:49] - Maximum available memory: 2048
store_1  | 19-05-13 08:51:12 1ad81424eddb INFO [blaze.core:50] - Number of available processors: 4
```

=== Manual

The installation should work under Windows, Linux and MacOS. Both Datomic and Blaze need a current Java 8 JRE. Other Versions of Java aren't currently tested.

==== Install Datomic

Blaze needs a https://www.datomic.com[Datomic] database to store FHIR® resources. Different editions of Datomic are available. Four our use case, the Free Edition is sufficient.

You can download Datomic Free here: https://my.datomic.com/downloads/free

Please download Version 0.9.5703 and unpack the ZIP into a directory of your choice. After that please follow the steps:

* open a terminal and change into the `datomic-free-0.9.5703` dir
* copy the sample properties file located at (relative) `config/samples/free-transactor-template.properties` to `config/transactor.properties`
* start the database by calling `bin/transactor config/transactor.properties`

The output should look like this:

```
Launching with Java options -server -Xms1g -Xmx1g -XX:+UseG1GC -XX:MaxGCPauseMillis=50
Starting datomic:free://localhost:4334/<DB-NAME>, storing data in: data ...
System started datomic:free://localhost:4334/<DB-NAME>, storing data in: data
```

You can change the data dir in the properties file if you like to have it at a different location.

==== Install Blaze

Blaze runs on the JVM and comes as single JAR file.
Download the most recent version https://github.com/life-research/blaze/releases/tag/v0.8.0-alpha.7[here].
Look for `blaze-0.8.0-alpha.7-standalone.jar`.
In addition to the JAR file, Blaze needs a set of FHIR® structure definitions to build it's database schema.
Please download and unpack the `fhir.zip` from the same location.

After the download, you can start blaze with the following command (Linux, MacOS):

```
DATABASE_URI=datomic:free://localhost:4334/db java -server -Xms2g -Xmx2g -XX:+UseG1GC -jar blaze-0.8.0-alpha.7-standalone.jar
```

Under Windows you need to set the Environment variables in the PowerShell before starting Blaze:

```
$Env:DATABASE_URI = "datomic:free://localhost:4334/db"
```

The output should look like this:

```
19-05-13 14:06:09 localhost INFO [blaze.system:109] - Read structure definitions from: fhir/r4/structure-definitions resulting in: Address, UsageContext, Annotation, Age, Attachment, Period, ContactDetail, DataRequirement, CodeableConcept, Organization, Encounter, CodeSystem, TriggerDefinition, Count, Specimen, Bundle, Expression, Coding, Dosage, Patient, Range, ContactPoint, Signature, RelatedArtifact, Timing, Meta, Quantity, Distance, HumanName, DeviceMetric, Duration, Money, SampledData, Ratio, Resource, Condition, Extension, ParameterDefinition, ServiceRequest, Device, Reference, Identifier, Narrative, Observation, Contributor
19-05-13 14:06:12 localhost INFO [blaze.system:89] - Created database at: datomic:free://localhost:4334/db
19-05-13 14:06:12 localhost INFO [blaze.system:92] - Connect with database: datomic:free://localhost:4334/db
19-05-13 14:06:13 localhost INFO [blaze.system:97] - Upsert schema in database: datomic:free://localhost:4334/db creating 10194 new facts
19-05-13 14:06:13 localhost INFO [blaze.server:33] - Start server on port 8080
19-05-13 14:06:13 localhost INFO [blaze.core:49] - Maximum available memory: 3641
19-05-13 14:06:13 localhost INFO [blaze.core:50] - Number of available processors: 8
```

The JVM Options `-server -Xms2g -Xmx2g -XX:+UseG1GC` are the default. You need to increase the Heap size if you have more data or the queries are slower than expected. You can use https://visualvm.github.io[VisualVM] to monitor the Heap size. Also https://prometheus.io[Prometheus] metrics will be available soon.

After installation, please refer to the https://github.com/life-research/blaze#usage[Usage] section of the README.

=== List of Environment Variables

Blaze is solely configured through these environment variables:

.Environment Variables
[cols="1,4", options="header,footer"]
|===
| Variable | Default | Description
| SERVER_PORT | 8080 | port of the main server with FHIR API
| METRICS_SERVER_PORT | 8081 | port of the metrics server
| LOG_LEVEL | info | one of trace, debug, info, warn, error
|===

== Monitoring

Blaze provides a https://prometheus.io[Prometheus] monitoring endpoint with various metrics. The endpoint lives on a different port `METRICS_SERVER_PORT` (defaults to 8081) because it should not be exposed to the outside like the normal FHIR API. The best way to explore the available metrics is to simply fetch it and read through the help texts.

== Open Source

Blaze is licenced under the Eclipse Public License and can be found on https://github.com/life-research/blaze[GitHub]. Please use the https://github.com/life-research/blaze/issues[Issue Tracker] if you have questions, feature requests or found a bug.

== Architecture

.Process-Level Architecture
[ditaa]
----
           +---------+  +---------+     +---------+
Logic Tier | Store 1 |  | Store 2 | ... | Store n |
           +------+--+  +------+--+     +---+-----+
                  ^            ^            ^
                  |            |            |
                  v            v            v
              +---+------------+------------+---+
Data Tier     | Datomic Transactor Free Version |
              |   with integrated H2 storage    |
              +---------------------------------+
----

.Store Architecture
[ditaa]
----
+-------------------------------+
| +-------------+ +-----------+ |
| |  FHIR API   | |  CQL API  | |
| +------+------+ +-----+-----+ |
|        |              ^       |
|        v              |       |
| +------+------+ +-----+-----+ |
| | Transaction | | CQL Query | |
| | Processor   | | Engine    | |
| +--+--------+-+ +-----+-----+ |
|    ^        |         ^       |
|    |        v         |       |
| +--+---+  +-+---------+-----+ |
| | FHIR |  |  Datomic Peer   | |
| | Prof.|  |  Library        | |
| +------+  +-----------------+ |
+-------------------------------+
----

.CQL Query Engine
[ditaa]
----
+-----------------------+
| CQL to ELM Translator |
+-----------------------+
| ELM to Expr Compiler  |
+-----------------------+
| Expr Evaluator        |
+-----------------------+
----

== Design Choices

=== References

One of the main goals of Blaze is to facilitate fast queries over a graph of resources. Performing such queries requires that all resources are available locally inside the database of Blaze. Besides that, referential integrity is important in order to allow for http://hl7.org/fhir/storage.html#joins[joins] and be able to walk the graph. For that reason, Blaze only allows https://www.hl7.org/fhir/codesystem-reference-handling-policy.html#reference-handling-policy-local[local] references and https://www.hl7.org/fhir/codesystem-reference-handling-policy.html#reference-handling-policy-enforced[enforces] referential integrity.

Currently, references have to be also https://www.hl7.org/fhir/codesystem-reference-handling-policy.html#reference-handling-policy-literal[literal] to ease implementation. This could change in the future.

== API

TODO

== Current Implementation State of ELM Expressions

The following table gives an overview of the current state of implementation of Expression Logical Model (ELM) expressions. In the state column, ✓ mean fully implemented, ! partly implemented (see notes) and ✗ not implemented jet.

.ELM Implementation State
[cols="2,3,1,4", options="header,footer"]
|===
| Group | Expression | State | Notes

1.1+<| 1. Simple Values
| 1.1. Literal | ! | only `Boolean`, `Integer`, `Decimal`, `String`

1.3+<|2. Structured Values
| 2.1. Tuple | ✗ |
| 2.2. Instance | ✗ |
| 2.3. Property | ! | no full FHIRPath

1.12+<|3. Clinical Values
| 3.1. Code | ✗ |
| 3.2. CodeDef | ✗ |
| 3.3. CodeRef | ! | only inside same library
| 3.4. CodeSystemDef | ✗ |
| 3.5. CodeSystemRef | ! | only inside same library
| 3.6. Concept | ✗ |
| 3.7. ConceptDef | ✗ |
| 3.8. ConceptRef | ✗ |
| 3.9. Quantity | ! | no unit
| 3.10. Ratio | ✗ |
| 3.11. ValueSetDef | ✗ |
| 3.12. ValueSetRef | ✗ |

1.6+<|4. Type Specifiers
| 4.1. TypeSpecifier | ✗ |
| 4.2. NamedTypeSpecifier | ✗ |
| 4.3. IntervalTypeSpecifier | ✗ |
| 4.4. ListTypeSpecifier | ✗ |
| 4.5. TupleTypeSpecifier | ✗ |
| 4.6. ChoiceTypeSpecifier | ✗ |

1.3+<|5. Libraries
| 5.1. Library | ✗ |
| 5.2. IncludeDef | ✗ |
| 5.3. VersionedIdentifier | ✗ |

1.1+<|6. Data Model
| 6.1. UsingDef | ✗ |

1.2+<|7. Parameters
| 7.1. ParameterDef | ✗ |
| 7.2. ParameterRef | ✗ |

1.7+<|8. Expressions
| 8.1. Expression | ✓ |
| 8.2. OperatorExpression | ✓ |
| 8.3. UnaryExpression | ✓ |
| 8.4. BinaryExpression | ✓ |
| 8.5. TernaryExpression | ✓ |
| 8.6. NaryExpression | ✓ |
| 8.7. AggregateExpression | ✓ |

1.4+<|9. Reusing Logic
| 9.1. ExpressionDef | ✓ |
| 9.2. ExpressionRef | ! | only inside same library
| 9.3. FunctionDef | ✗ |
| 9.4. FunctionRef | ! | hard coded implementation of `ToQuantity` and `ToDateTime`

1.13+<|10. Queries
| 10.1. Query | ✓ |
| 10.2. AliasedQuerySource | ! | only single source
| 10.3. AliasRef | ✓ |
| 10.4. ByColumn | ✗ |
| 10.5. ByDirection | ✗ |
| 10.6. ByExpression | ✗ |
| 10.7. LetClause | ✗ |
| 10.8. QueryLetRef | ✗ |
| 10.9. RelationshipClause | ✓ |
| 10.10. ReturnClause | ! | always distinct
| 10.11. SortClause | ✗ |
| 10.12. With | ! | only equiv version
| 10.13. Without | ✗ |

1.1+<|11. External Data
| 11.1. Retrieve | ! | no date ranges

1.7+<|12. Comparison Operators
| 12.1. Equal | ✓ |
| 12.2. Equivalent | ✗ |
| 12.3. Greater | ✓ |
| 12.4. GreaterOrEqual | ✓ |
| 12.5. Less | ✓ |
| 12.6. LessOrEqual | ✓ |
| 12.7. NotEqual | ✓ |

1.5+<|13. Logical Operators
| 13.1. And | ✓ |
| 13.2. Implies | ✓ |
| 13.3. Not | ✓ |
| 13.4. Or | ✓ |
| 13.5. Xor | ✓ |

1.5+<|14. Nullological Operators
| 14.1. Null | ✓ |
| 14.2. Coalesce | ✓ |
| 14.3. IsFalse | ✓ |
| 14.4. IsNull | ✓ |
| 14.5. IsTrue | ✓ |

1.2+<|15. Conditional Operators
| 15.1. Case | ✓ |
| 15.2. If | ✓ |

1.20+<|16. Arithmetic Operators
| 16.1. Abs | ✓ |
| 16.2. Add | ✓ |
| 16.3. Ceiling | ✓ |
| 16.4. Divide | ✓ |
| 16.5. Exp | ✓ |
| 16.6. Floor | ✓ |
| 16.7. Log | ✓ |
| 16.8. Ln | ✓ |
| 16.9. MaxValue | ✓ |
| 16.10. MinValue | ✓ |
| 16.11. Modulo | ✓ |
| 16.12. Multiply | ✓ |
| 16.13. Negate | ✓ |
| 16.14. Power | ✓ |
| 16.15. Predecessor | ✓ |
| 16.16. Round | ✓ |
| 16.17. Subtract | ✓ |
| 16.18. Successor | ✓ |
| 16.19. Truncate | ✓ |
| 16.20. TruncatedDivide | ✓ |

1.18+<|17. String Operators
| 17.1. Combine | ✓ |
| 17.2. Concatenate | ✓ |
| 17.3. EndsWith | ✓ |
| 17.4. Equal | ✓ |
| 17.5. Equivalent | ✗ |
| 17.6. Indexer | ✓ |
| 17.7. LastPositionOf | ✓ |
| 17.8. Length | ✓ |
| 17.9. Lower | ✓ |
| 17.10. Matches | ✓ |
| 17.11. Not Equal | ✓ |
| 17.12. PositionOf | ✓ |
| 17.13. ReplaceMatches | ✓ |
| 17.14. Split | ✓ |
| 17.15. SplitOnMatches | ✗ |
| 17.16. StartsWith | ✓ |
| 17.17. Substring | ✓ |
| 17.18. Upper | ✓ |

1.22+<|18. Date and Time Operators
| 18.1. Add | ✓ |
| 18.2. After | ✓ |
| 18.3. Before | ✓ |
| 18.4. Equal | ✓ |
| 18.5. Equivalent | ✓ |
| 18.6. Date | ✓ |
| 18.7. DateFrom | ✓ |
| 18.8. DateTime | ✓ |
| 18.9. DateTimeComponentFrom | ✓ |
| 18.10. DifferenceBetween | ! | same as DurationBetween
| 18.11. DurationBetween | ✓ |
| 18.12. Not Equal | ✓ |
| 18.13. Now | ✓ |
| 18.14. SameAs | ✓ |
| 18.15. SameOrBefore | ✓ |
| 18.16. SameOrAfter | ✓ |
| 18.17. Subtract | ✓ |
| 18.18. Time | ✓ |
| 18.19. TimeFrom | ✓ |
| 18.20. TimezoneOffsetFrom | ✓ |
| 18.21. TimeOfDay | ✓ |
| 18.22. Today | ✓ |

1.31+<|19. Interval Operators
| 19.1. Interval | ✓ |
| 19.2. After | ✓ |
| 19.3. Before | ✓ |
| 19.4. Collapse | ✓ |
| 19.5. Contains | ✓ |
| 19.6. End | ✓ |
| 19.7. Ends | ✓ |
| 19.8. Equal | ✓ |
| 19.9. Equivalent | ✓ |
| 19.10. Except | ✓ |
| 19.11. Expand | ✗ |
| 19.12. In | ✓ |
| 19.13. Includes | ✓ |
| 19.14. IncludedIn | ✓ |
| 19.15. Intersect | ✓ |
| 19.16. Meets | ✓ |
| 19.17. MeetsBefore | ✓ |
| 19.18. MeetsAfter | ✓ |
| 19.19. Not Equal | ✓ |
| 19.20. Overlaps | ✓ |
| 19.21. OverlapsBefore | ✓ |
| 19.22. OverlapsAfter | ✓ |
| 19.23. PointFrom | ✓ |
| 19.24. ProperContains | ✓ |
| 19.25. ProperIn | ✓ |
| 19.26. ProperIncludes | ✓ |
| 19.27. ProperIncludedIn | ✓ |
| 19.28. Start | ✓ |
| 19.29. Starts | ✓ |
| 19.31. Union | ✓ |
| 19.31. Width | ✓ |

1.29+<|20. List Operators
| 20.1. List | ✓ |
| 20.2. Contains | ✓ |
| 20.3. Current | ✓ |
| 20.4. Distinct | ✓ |
| 20.5. Equal | ✓ |
| 20.6. Equivalent | ✓ |
| 20.7. Except | ✓ |
| 20.8. Exists | ✓ |
| 20.9. Filter | ✓ |
| 20.10. First | ✓ |
| 20.11. Flatten | ✓ |
| 20.12. ForEach | ✓ |
| 20.13. In | ✓ |
| 20.14. Includes | ✓ |
| 20.15. IncludedIn | ✓ |
| 20.16. IndexOf | ✓ |
| 20.17. Intersect | ✓ |
| 20.18. Last | ✓ |
| 20.19. Not Equal | ✓ |
| 20.20. ProperContains | ✓ |
| 20.21. ProperIn | ✓ |
| 20.22. ProperIncludes | ✓ |
| 20.23. ProperIncludedIn | ✓ |
| 20.24. Repeat | ✗ |
| 20.25. SingletonFrom | ✓ |
| 20.26. Slice | ✓ |
| 20.27. Sort | ✓ |
| 20.28. Times | ✗ |
| 20.29. Union | ✓ |

1.15+<|21. Aggregate Operators
| 21.1. AllTrue | ! | no path
| 21.2. AnyTrue | ! | no path
| 21.3. Avg | ! | no path
| 21.4. Count | ! | no path
| 21.5. GeometricMean | ! | no path
| 21.6. Product | ! | no path
| 21.7. Max | ! | no path
| 21.8. Median | ! | no path
| 21.9. Min | ! | no path
| 21.10. Mode | ! | no path
| 21.11. PopulationVariance | ! | no path
| 21.12. PopulationStdDev | ! | no path
| 21.13. Sum | ! | no path
| 21.14. StdDev | ! | no path
| 21.15. Variance | ! | no path

1.29+<|22. Type Operators
| 22.1. As | ! | no strictness
| 22.2. CanConvert | ✗ |
| 22.3. CanConvertQuantity | ✗ |
| 22.4. Children | ✗ |
| 22.5. Convert | ✗ |
| 22.6. ConvertQuantity | ✗ |
| 22.7. ConvertsToBoolean | ✗ |
| 22.8. ConvertsToDate | ✗ |
| 22.9. ConvertsToDateTime | ✗ |
| 22.10. ConvertsToDecimal | ✗ |
| 22.11. ConvertsToInteger | ✗ |
| 22.12. ConvertsToQuantity | ✗ |
| 22.13. ConvertsToRatio | ✗ |
| 22.14. ConvertsToString | ✗ |
| 22.15. ConvertsToTime | ✗ |
| 22.16. Descendents | ✗ |
| 22.17. Is | ✗ |
| 22.18. ToBoolean | ✗ |
| 22.19. ToChars | ✗ |
| 22.20. ToConcept | ✗ |
| 22.21. ToDate | ✗ |
| 22.22. ToDateTime | ! |
| 22.23. ToDecimal | ✓ |
| 22.24. ToInteger | ✓ |
| 22.25. ToList | ✓ |
| 22.26. ToQuantity | ✗ |
| 22.27. ToRatio | ✗ |
| 22.28. ToString | ✓ |
| 22.29. ToTime | ✗ |

1.11+<|23. Clinical Operators
| 23.1. AnyInCodeSystem | ✗ |
| 23.2. AnyInValueSet | ✗ |
| 23.3. CalculateAge | ✓ |
| 23.4. CalculateAgeAt | ✓ |
| 23.5. Equal | ✓ |
| 23.6. Equivalent | ✗ |
| 23.7. InCodeSystem | ✗ |
| 23.8. InValueSet | ✗ |
| 23.9. Not Equal | ✓ |
| 23.10. SubsumedBy | ✗ |
| 23.11. Subsumes | ✗ |

1.1+<|24. Errors and Messages
| 24.1. Message | ✗ |

| | 2+<| ✓ = 151, ! = 29, ✗ = 70, 66 % finished
|===

== Performance

=== FHIR Update Interaction

We use the following resources in single update interactions.

.Patient
[source,json]
----
{
  "resourceType": "Patient",
  "id": "0",
  "gender": "male",
  "birthDate": "1994-01-10"
}
----

.Condition
[source,json]
----
{
  "resourceType" : "Condition",
  "id" : "0-0",
  "subject" : {
    "reference" : "Patient/0"
  },
  "code" : {
    "coding" : [ {
      "system" : "http://hl7.org/fhir/sid/icd-10",
      "version" : "2016",
      "code" : "C70"
    } ]
  },
  "onsetDateTime" : "2006-08-09"
}
----

.Observation
[source,json]
----
{
  "resourceType" : "Observation",
  "id" : "0-0-body-weight",
  "status" : "final",
  "subject" : {
    "reference" : "Patient/0"
  },
  "code" : {
    "coding" : [ {
      "system" : "http://loinc.org",
      "code" : "29463-7"
    } ]
  },
  "valueQuantity" : {
    "value" : 103.2,
    "unit" : "kg"
  },
  "effectiveDateTime" : "2006-08-09"
}
----

.Specimen
[source,json]
----
{
  "resourceType" : "Specimen",
  "id" : "0",
  "subject" : {
    "reference" : "Patient/0"
  },
  "type" : {
    "coding" : [ {
      "system" : "http://germanbiobanknode.de/fhir/code-systems/sample-liquid",
      "code" : "serum"
    } ]
  },
  "collection" : {
    "collectedDateTime" : "2006-08-09"
  }
}
----

Results of performance tests using https://github.com/tsenart/vegeta[vegeta] running for 30 s each.

Blaze was started with `-server -Xms2g -Xmx2g -XX:+UseG1GC` and Datomic v0.9.5703 with `-server -Xms1g -Xmx1g -XX:+UseG1GC -XX:MaxGCPauseMillis=50` both running JRE 1.8.0_212.

.Results
[cols="1,1,1,1,1,1", options="header,footer"]
|===
| Resource Type | Rate | Mean | Median | Q-95 | Q-99
| Patient | 600 | 10 ms | 5.6 ms | 27 ms | 110 ms
| Condition | 600 | 18 ms | 6.9 ms | 58 ms | 250 ms
| Observation | 600 | 22 ms | 8.4 ms | 85 ms | 300 ms
| Specimen | 600 | 28 ms | 8.1 ms | 91 ms | 480 ms
|===

The results show that Blaze is able to handle 600 updates per second with a 99% quantile of response times of less than half a second.

== Implementation

=== Threading Model

Blaze uses the https://aleph.io/aleph/http.html[Aleph HTTP server] which is able to process requests asynchronously. Aleph doesn't need one thread per request processing. Instead it uses a low number of threads to handle I/O for multiple requests buffering HTTP headers and bodies. Once a request is fully received, a worker thread is used to calculate the response. In case the response calculation needs to perform I/O itself, like connecting to the Datomic transactor for writes, it uses https://aleph.io/manifold/deferreds.html[Manifold Deferreds] to do that asynchronously as well. Doing so makes all other request processing CPU bound. For that reason Blaze uses a single https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/Executors.html#newWorkStealingPool--[work-stealing thread pool] with the parallelism level set to the number of available cores for all it's request processing.

For transactions, Blaze has to do I/O. The transaction data is send to the Datomic transactor and Blaze has to wait for the answer. In order to maximize the throughput of the transactor, Blaze uses a parallelism level of 20 while sending data to it. Again a work-stealing thread pool is used to achieve and maintain that parallelism level.

Currently the queues in front of both thread pools are unbounded. Future work should focus on ways to introduce timeouts or bounded queues.

=== 3-valued Logic and Set Theory

CQL seems to use a Kleene K3 logic which is also used in SQL.

https://en.wikipedia.org/wiki/Three-valued_logic#SQL
http://www.cse.unsw.edu.au/~meyden/research/indef-review.ps

=== Decimal Arithmetic

http://speleotrove.com/decimal/


=== Data Types

.Mapping of FHIR Primitive Types to Datomic Data Types
[cols="1,1,1", options="header,footer"]
|===
| FHIR Type | Datomic Type | Byte Codes
| boolean | boolean |
| integer | long |
| string | string |
| decimal | bytes | 6, 7, 8, 9, 10
| uri | string |
| url | string |
| canonical | string |
| base64Binary | bytes |
| instant | instant |
| date | bytes | 0, 1, 2
| dateTime | bytes | 0, 1, 2, 4, 5
| time | bytes | 3
| code | string |
| oid | string |
| id | string |
| markdown | string |
| unsignedInt | long |
| positiveInt | long |
| uuid | uuid |
|===

.Mapping of FHIR Complex Types to Datomic Data Types
[cols="1,1,1,3", options="header,footer"]
|===
| FHIR Type | Datomic Type | Byte Codes | Comment
| Quantity | bytes | 12 | only value followed by unit
|===
