{fhir/integer clojure.core/int
 fhir/long clojure.core/long
 fhir/uri blaze.fhir.spec.type/uri
 fhir/url blaze.fhir.spec.type/->Url
 fhir/canonical blaze.fhir.spec.type/canonical
 fhir/base64Binary blaze.fhir.spec.type/->Base64Binary
 fhir/instant blaze.fhir.spec.type/->Instant
 fhir/date blaze.fhir.spec.type/->Date
 fhir/dateTime blaze.fhir.spec.type/->DateTime
 fhir/time blaze.fhir.spec.type/->Time
 fhir/code blaze.fhir.spec.type/tagged-literal->Code
 fhir/oid blaze.fhir.spec.type/->Oid
 fhir/id blaze.fhir.spec.type/->Id
 fhir/markdown blaze.fhir.spec.type/->Markdown
 fhir/unsignedInt blaze.fhir.spec.type/->UnsignedInt
 fhir/positiveInt blaze.fhir.spec.type/->PositiveInt
 fhir/uuid blaze.fhir.spec.type/->Uuid
 fhir/xhtml blaze.fhir.spec.type/->Xhtml
 fhir/Attachment blaze.fhir.spec.type/map->Attachment
 fhir/Extension blaze.fhir.spec.type/map->Extension
 fhir/Coding blaze.fhir.spec.type/map->Coding
 fhir/CodeableConcept blaze.fhir.spec.type/codeable-concept
 fhir/Quantity blaze.fhir.spec.type/map->Quantity
 fhir/Period blaze.fhir.spec.type/map->Period
 fhir/Identifier blaze.fhir.spec.type/map->Identifier
 fhir/HumanName blaze.fhir.spec.type/map->HumanName
 fhir/Address blaze.fhir.spec.type/map->Address
 fhir/Reference blaze.fhir.spec.type/map->Reference
 fhir/Meta blaze.fhir.spec.type/mk-meta
 fhir/BundleEntrySearch blaze.fhir.spec.type/map->BundleEntrySearch
 system/date blaze.fhir.spec.type.system/parse-date
 system/date-time blaze.fhir.spec.type.system/parse-date-time}
