{blaze/hash blaze.fhir.hash/from-hex
 blaze/hash-prefix blaze.fhir.hash/prefix-from-hex
 blaze/field-name blaze.fhir.spec.type.json/field-name
 fhir/boolean blaze.fhir.spec.type/boolean
 fhir/integer blaze.fhir.spec.type/integer
 fhir/integer64 blaze.fhir.spec.type/integer64
 fhir/string blaze.fhir.spec.type/string
 fhir/decimal blaze.fhir.spec.type/decimal
 fhir/uri blaze.fhir.spec.type/uri
 fhir/url blaze.fhir.spec.type/url
 fhir/canonical blaze.fhir.spec.type/canonical
 fhir/base64Binary blaze.fhir.spec.type/base64Binary
 fhir/instant blaze.fhir.spec.type/instant
 fhir/date blaze.fhir.spec.type/date
 fhir/dateTime blaze.fhir.spec.type/dateTime
 fhir/time blaze.fhir.spec.type/time
 fhir/code blaze.fhir.spec.type/code
 fhir/oid blaze.fhir.spec.type/oid
 fhir/id blaze.fhir.spec.type/id
 fhir/markdown blaze.fhir.spec.type/markdown
 fhir/unsignedInt blaze.fhir.spec.type/unsignedInt
 fhir/positiveInt blaze.fhir.spec.type/positiveInt
 fhir/uuid blaze.fhir.spec.type/uuid
 fhir/xhtml blaze.fhir.spec.type/->Xhtml
 fhir/Attachment blaze.fhir.spec.type/attachment
 fhir/Extension blaze.fhir.spec.type/extension
 fhir/Coding blaze.fhir.spec.type/coding
 fhir/CodeableConcept blaze.fhir.spec.type/codeable-concept
 fhir/Quantity blaze.fhir.spec.type/quantity
 fhir/Ratio blaze.fhir.spec.type/ratio
 fhir/Period blaze.fhir.spec.type/period
 fhir/Identifier blaze.fhir.spec.type/identifier
 fhir/HumanName blaze.fhir.spec.type/human-name
 fhir/Address blaze.fhir.spec.type/address
 fhir/Reference blaze.fhir.spec.type/reference
 fhir/Meta blaze.fhir.spec.type/meta
 fhir/BundleEntrySearch blaze.fhir.spec.type/bundle-entry-search
 fhir/CodeableReference blaze.fhir.spec.type/codeable-reference
 system/date blaze.fhir.spec.type.system/parse-date
 system/date-time blaze.fhir.spec.type.system/parse-date-time
 system/time blaze.fhir.spec.type.system/parse-time}
