name: Publish Release

on:
  release:
    types: [ released ]

# Declare default permissions as read-only.
permissions: read-all

jobs:
  pages:
    if: github.event.release.target_commitish == 'main'
    runs-on: ubuntu-24.04
    permissions:
      actions: write
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
      with:
        egress-policy: audit

    - name: Trigger Pages Build
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh workflow run Docs --ref main --repo ${{ github.repository }}
