name: Publish Release

on:
  release:
    types: [ released ]

# Declare default permissions as read-only.
permissions: read-all

jobs:
  pages:
    if: github.event.release.target_commitish == 'main'
    runs-on: ubuntu-24.04
    permissions:
      actions: write
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
      with:
        egress-policy: audit

    - name: Trigger Pages Build
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh workflow run Docs --ref main --repo ${{ github.repository }}
